version: '3.8'

services:
  # Container principal com o codigo
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    command: sleep infinity
    volumes:
      - ..:/workspace:cached

  # container do bd
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # senha pra desenvolvimento
      - POSTGRES_DB=parking_db # nome do banco de dados
      - TZ=America/Sao_Paulo
    ports:
      - '5432:5432'

volumes:
  postgres-data: